disabled_rules: # rule identifiers to exclude from running
  - opening_brace
  - function_parameter_count
  - trailing_whitespace
  - vertical_parameter_alignment
opt_in_rules: # some rules are only opt-in
  - empty_count
included: # paths to include during linting. `--path` is ignored if present.
  - Color
  - Domain
  - Platform
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Color/Sources/Generated
  - Domain/Generated
force_cast: warning 
force_try: warning
line_length: 140
file_length:
  warning: 300
  error: 700
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded:
    - Key
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey
    - Self
    - x
    - y
    - z
    - no
    - _self
